/**
 * OrderBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Address } from './address';


export interface Customer { 
    id?: number;
    firstName?: string | null;
    lastName?: string | null;
    addressId?: number;
    address?: Address;
    readonly orders?: Array<Order> | null;
}

