/**
 * OrderBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { SubCategory } from './subCategory';


export interface MeatPiece { 
    id?: number;
    name?: string | null;
    pricePerKg?: number;
    subCategoryId?: number;
    readonly articles?: Array<Article> | null;
    subCategory?: SubCategory;
}

