/**
 * OrderBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeatPiece } from './meatPiece';
import { Customer } from './customer';
import { SalesDay } from './salesDay';


export interface Order { 
    id?: number;
    customerId?: number;
    salesDayId?: number;
    amount?: number;
    paidStatus?: string | null;
    date?: string;
    notes?: string | null;
    meatPieceId?: number;
    salesDay?: SalesDay;
    meatPiece?: MeatPiece;
    customer?: Customer;
}

