/**
 * OrderBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { Article } from './article';


export interface Order { 
    id?: number;
    customerId?: number;
    date?: string;
    readonly articles?: Array<Article> | null;
    customer?: Customer;
}

