@baseUrl = http://localhost:5000


################################################## Category
DELETE {{baseUrl}}/api/Category/deleteMeatPiecePart?meatPiecePartId=1
#####
GET {{baseUrl}}/api/Category/getAllCategories
#####
GET {{baseUrl}}/api/Category/getAllMeatPieaces
#####
GET {{baseUrl}}/api/Category/MeatPieceById?meatPieceId=1
#####
GET {{baseUrl}}/api/Category/MeatPieceNumberofParts?meatPieceId=1
#####
GET {{baseUrl}}/api/Category/MeatPiecePartsFromMeatPiece?meatPieceId=1
#####
GET {{baseUrl}}/api/Category/MeatPiecesBySubCategoryId?subCategoryId=1
#####
GET {{baseUrl}}/api/Category/StockByCategoryId?categoryId=1
#####
GET {{baseUrl}}/api/Category/StockByMeatPieceId?meatPieceId=1
#####
GET {{baseUrl}}/api/Category/SubCategoriesByCategoryId?categoryId=1
#####
GET {{baseUrl}}/api/Category/SubCategoryTotalStock?subCategoryId=1
#####
POST {{baseUrl}}/api/Category/addMeatPiecePart
#####
POST {{baseUrl}}/api/Category/readCategories
#####
PUT {{baseUrl}}/api/Category/setMeatPiecePricePerKg?meatPieceId=1&pricePerKg=1
#####

################################################## Customer
DELETE {{baseUrl}}/api/Customer/deleteCustomer
#####
GET {{baseUrl}}/api/Customer/getAllCustomers
#####
POST {{baseUrl}}/api/Customer/addNewCustomer
#####
POST {{baseUrl}}/api/Customer/ReadCustomers
#####
PUT {{baseUrl}}/api/Customer/editCustomer
#####

################################################## Order
DELETE {{baseUrl}}/Order/Order?deleteOrderId=1
#####
GET {{baseUrl}}/Order/CategoryNameFromOrder?orderId=1
#####
GET {{baseUrl}}/Order/Orders
#####
GET {{baseUrl}}/Order/OrdersByCustomer?customerId=1
#####
GET {{baseUrl}}/Order/OrdersCount?dateFrom=abc&dateTo=abc
#####
GET {{baseUrl}}/Order/OrdersForDashboard?startDate=abc&endDate=abc
#####
GET {{baseUrl}}/Order/OrdersForSalesDay?salesDayId=1
#####
GET {{baseUrl}}/Order/OrdersFromCustomerForSalesDay?customerId=1&salesDayId=1
#####
GET {{baseUrl}}/Order/RevenueForTimeSpan?dateFrom=abc&dateTo=abc
#####
GET {{baseUrl}}/Order/UnpaidOrdersCount?dateFrom=abc&dateTo=abc
#####
POST {{baseUrl}}/Order/Order
#####
POST {{baseUrl}}/Order/PayForOrder?orderId=1
#####

################################################## SalesDay
DELETE {{baseUrl}}/api/SalesDay/SalesDay?salesDayId=1
#####
GET {{baseUrl}}/api/SalesDay/getOxes?salesDayId=1
#####
GET {{baseUrl}}/api/SalesDay/getSalesDays
#####
POST {{baseUrl}}/api/SalesDay/addOx?salesDayId=1&ox=abc
#####
POST {{baseUrl}}/api/SalesDay/addSalesDay
#####
