@baseUrl = http://localhost:5000


################################################## Category
GET {{baseUrl}}/api/Category/getAllCategories
#####
GET {{baseUrl}}/api/Category/getAllMeatPieaces
#####
GET {{baseUrl}}/api/Category/getStockForSubCategoryId?subCategoryId=1
#####
GET {{baseUrl}}/api/Category/MeatPiecesBySubCategoryId?subCategoryId=1
#####
GET {{baseUrl}}/api/Category/SubCategoriesByCategoryId?categoryId=1
#####
POST {{baseUrl}}/api/Category/readCategories
#####
PUT {{baseUrl}}/api/Category/addStockForSubCategory?subCategoryId=1&newStock=1
#####
PUT {{baseUrl}}/api/Category/updateStockForMeatPiece?meatPieceId=1&newStock=1
#####
PUT {{baseUrl}}/api/Category/updateStockForSubCategory?subCategoryId=1&newStock=1
#####

################################################## Customer
DELETE {{baseUrl}}/api/Customer/deleteCustomer
Content-type: application/json

{
      "id": 1,
      "name": "abc",
      "address": "abc"
   }
#####
GET {{baseUrl}}/api/Customer/getAllCustomers
#####
POST {{baseUrl}}/api/Customer/addNewCustomer
Content-type: application/json

{
   "name": "abc",
   "address": "abc"
}
#####
POST {{baseUrl}}/api/Customer/ReadCustomers
#####
PUT {{baseUrl}}/api/Customer/editCustomer
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "address": "abc"
}
#####

################################################## Order
DELETE {{baseUrl}}/Order/Order?deleteOrderId=1
#####
GET {{baseUrl}}/Order/Orders
#####
GET {{baseUrl}}/Order/OrdersByCustomer?customerId=1
#####
GET {{baseUrl}}/Order/OrdersForSalesDay?salesDayId=1
#####
GET {{baseUrl}}/Order/OrdersFromCustomerForSalesDay?customerId=1&salesDayId=1
#####
POST {{baseUrl}}/Order/Order
Content-type: application/json

{
         "id": 1,
         "dateString": "abc",
         "amount": 1,
      "paidStatus": "abc",
      "customerId": 1,
   "deposit": 1,
   "price": 1,
   "salesDayId": 1,
   "notes": "abc",
   "meatPieceId": 1
}
#####

################################################## SalesDay
DELETE {{baseUrl}}/api/SalesDay/SalesDay?salesDayId=1
#####
GET {{baseUrl}}/api/SalesDay/getSalesDays
#####
POST {{baseUrl}}/api/SalesDay/addSalesDay
Content-type: application/json

{
         "id": 1,
      "name": "abc",
      "dateString": "abc"
   }
#####
